const restaurants = [
  {name:'Masala House', cuisine:'Indian · North Indian', time:'25–30 min', rating:'4.8', category:'Indian', tag:'MOST LOVED', price:320, image:'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=700&q=85'},
  {name:'Farro & Co.', cuisine:'Italian · Pasta · Pizza', time:'30–35 min', rating:'4.7', category:'Italian', tag:'TOP RATED', price:450, image:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=700&q=85'},
  {name:'Soba Social', cuisine:'Japanese · Asian', time:'20–25 min', rating:'4.9', category:'Asian', tag:'FAST DELIVERY', price:390, image:'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=700&q=85'},
  {name:'Bun & Beyond', cuisine:'Burgers · American', time:'25–30 min', rating:'4.6', category:'Burgers', tag:'HOT RIGHT NOW', price:280, image:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=85'},
  {name:'Green Theory', cuisine:'Salads · Healthy', time:'20–25 min', rating:'4.8', category:'Healthy', tag:'FEEL GOOD', price:360, image:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=700&q=85'},
  {name:'Butter & Bloom', cuisine:'Desserts · Bakery', time:'25–30 min', rating:'4.9', category:'Desserts', tag:'SWEET PICK', price:240, image:'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=700&q=85'}
];
let activeCategory = 'All'; let cart = [];
const grid = document.getElementById('restaurantGrid'); const count = document.getElementById('cartCount');
function renderRestaurants(){ const shown = restaurants.filter(r => activeCategory === 'All' || r.category === activeCategory); grid.innerHTML = shown.map(r => `<article class="restaurant-card"><div class="restaurant-image"><img src="${r.image}" alt="${r.name} food" /><span class="tag">${r.tag}</span></div><div class="restaurant-info"><div class="restaurant-title-line"><h3>${r.name}</h3><span class="rating"><span>★</span> ${r.rating}</span></div><p>${r.cuisine}</p><div class="restaurant-bottom"><span>${r.time}</span><button class="add-button" data-name="${r.name}" aria-label="Add ${r.name} to basket">+</button></div></div></article>`).join(''); }
function format(n){ return `₹${n.toLocaleString('en-IN')}`; }
function renderCart(){ count.textContent = cart.length; const holder = document.getElementById('cartItems'); const summary = document.getElementById('cartSummary'); if(!cart.length){holder.innerHTML='<div class="empty-cart"><span>☕</span><p>Your basket is empty.</p><small>Add something delicious to get started.</small></div>'; summary.hidden=true; return;} holder.innerHTML = cart.map((r,i)=>`<div class="cart-item"><img src="${r.image}" alt=""/><div><h3>${r.name}</h3><small>${r.cuisine}</small></div><div><b>${format(r.price)}</b><button class="remove-item" data-index="${i}" aria-label="Remove ${r.name}">×</button></div></div>`).join(''); const subtotal=cart.reduce((s,r)=>s+r.price,0); document.getElementById('subtotal').textContent=format(subtotal); document.getElementById('total').textContent=format(subtotal+39); summary.hidden=false; }
function addToCart(name){ cart.push(restaurants.find(r=>r.name===name)); renderCart(); openCart(); showToast(`${name} added to your basket`); }
function openCart(){document.getElementById('cartPanel').classList.add('open');document.getElementById('overlay').classList.add('show');document.getElementById('cartPanel').setAttribute('aria-hidden','false')}
function closeCart(){document.getElementById('cartPanel').classList.remove('open');document.getElementById('overlay').classList.remove('show');document.getElementById('cartPanel').setAttribute('aria-hidden','true')}
let toastTimer; function showToast(message){const toast=document.getElementById('toast');toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}
document.addEventListener('click', e=>{const add=e.target.closest('.add-button');if(add)addToCart(add.dataset.name);const remove=e.target.closest('.remove-item');if(remove){cart.splice(remove.dataset.index,1);renderCart();}});
document.querySelectorAll('.category').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.category.active').classList.remove('active');button.classList.add('active');activeCategory=button.dataset.category;renderRestaurants();}));
document.getElementById('cartButton').addEventListener('click',openCart);document.getElementById('closeCart').addEventListener('click',closeCart);document.getElementById('overlay').addEventListener('click',closeCart);
document.getElementById('menuToggle').addEventListener('click',()=>document.querySelector('.desktop-nav').classList.toggle('mobile-open'));
document.querySelectorAll('.desktop-nav a').forEach(link=>link.addEventListener('click',()=>document.querySelector('.desktop-nav').classList.remove('mobile-open')));
document.getElementById('searchForm').addEventListener('submit',e=>{e.preventDefault();const term=document.getElementById('foodSearch').value.trim().toLowerCase();if(!term)return showToast('Try searching for a dish or cuisine');const match=restaurants.find(r=>(r.name+r.cuisine+r.category).toLowerCase().includes(term));if(match){activeCategory=match.category;document.querySelectorAll('.category').forEach(b=>b.classList.toggle('active',b.dataset.category===activeCategory));renderRestaurants();document.getElementById('restaurants').scrollIntoView({behavior:'smooth'});showToast(`Showing ${match.category} picks`)}else showToast('No nearby matches yet — try another search.');});
document.getElementById('locationButton').addEventListener('click',()=>showToast('Delivery location: Bengaluru'));document.getElementById('offerButton').addEventListener('click',()=>showToast('Offer code HELLOPLATERA copied!'));document.getElementById('checkoutButton').addEventListener('click',()=>showToast('Checkout is ready for your order.'));document.getElementById('allCuisines').addEventListener('click',()=>showToast('More cuisines coming soon!'));
['prevRestaurant','nextRestaurant'].forEach(id=>document.getElementById(id).addEventListener('click',()=>grid.scrollBy({left:id==='nextRestaurant'?350:-350,behavior:'smooth'})));
renderRestaurants();renderCart();
